const RELATION_TYPES = {
    SPOUSE: 'SPOUSE',
    FATHER: 'FATHER',
    MOTHER: 'MOTHER',
    SON: 'SON',
    DAUGHTER: 'DAUGHTER',
    BROTHER: 'BROTHER',
    SISTER: 'SISTER',
    FATHER_IN_LAW: 'FATHER_IN_LAW',
    MOTHER_IN_LAW: 'MOTHER_IN_LAW',
    SON_IN_LAW: 'SON_IN_LAW',
    DAUGHTER_IN_LAW: 'DAUGHTER_IN_LAW',
    UNCLE: 'UNCLE',
    AUNT: 'AUNT',
    NEPHEW: 'NEPHEW',
    NIECE: 'NIECE',
    GRANDFATHER: 'GRANDFATHER',
    GRANDMOTHER: 'GRANDMOTHER',
    GRANDSON: 'GRANDSON',
    GRANDDAUGHTER: 'GRANDDAUGHTER',
    OTHER: 'OTHER',
  };
  
  module.exports = { RELATION_TYPES };